/**
 * This code was generated by AI based on user directions and a natural language description of the algorithm.
 * The algorithm generates insights from academic datasets by:
 * 1. Finding top departments by total enrollment
 * 2. Computing historical averages for those departments
 * 3. Identifying top courses by enrollment within each department
 * 4. Finding highest-average courses within each department
 */

import InsightFacade from "./InsightFacade";
import {InsightDatasetKind, InsightResult} from "./IInsightFacade";

export interface DepartmentInsight {
	dept: string;
	totalEnrollment: number;
	historicalAverage: number;
	topCourses: CourseInsight[];
	highestAverageCourses: CourseInsight[];
}

export interface CourseInsight {
	dept: string;
	id: string;
	title: string;
	enrollment: number;
	average: number;
}

export class DatasetInsights {
	private static readonly TOP_DEPARTMENTS_COUNT = 3;
	private static readonly TOP_COURSES_PER_DEPT = 5;
	private static readonly HIGHEST_AVG_COURSES_COUNT = 4;
	private static readonly YEARS_LOOKBACK = 10;

	private facade: InsightFacade;

	constructor(facade: InsightFacade) {
		this.facade = facade;
	}

	public async generateInsights(datasetId: string): Promise<DepartmentInsight[]> {
		const topDepartments = await this.getTopDepartmentsByEnrollment(datasetId);
		const insights: DepartmentInsight[] = [];

		for (const dept of topDepartments) {
			const historicalAvg = await this.getDepartmentHistoricalAverage(datasetId, dept.dept);
			const topCourses = await this.getTopCoursesByEnrollment(datasetId, dept.dept);
			const highestAvgCourses = await this.getHighestAverageCourses(datasetId, dept.dept);

			insights.push({
				dept: dept.dept,
				totalEnrollment: dept.totalEnrollment,
				historicalAverage: historicalAvg,
				topCourses: topCourses.slice(0, DatasetInsights.TOP_COURSES_PER_DEPT),
				highestAverageCourses: highestAvgCourses.slice(0, DatasetInsights.HIGHEST_AVG_COURSES_COUNT)
			});
		}

		return insights;
	}

	private async getTopDepartmentsByEnrollment(datasetId: string): Promise<Array<{dept: string, totalEnrollment: number}>> {
		const query = {
			WHERE: {},
			OPTIONS: {
				COLUMNS: [`${datasetId}_dept`, "totalEnrollment"],
				ORDER: {
					dir: "DOWN",
					keys: ["totalEnrollment"]
				}
			},
			TRANSFORMATIONS: {
				GROUP: [`${datasetId}_dept`],
				APPLY: [{
					totalEnrollment: {
						SUM: `${datasetId}_pass`
					}
				}]
			}
		};

		try {
			const results = await this.facade.performQuery(query);
			return results.slice(0, DatasetInsights.TOP_DEPARTMENTS_COUNT).map((r: InsightResult) => ({
				dept: r[`${datasetId}_dept`] as string,
				totalEnrollment: r.totalEnrollment as number
			}));
		} catch (error) {
			// If ResultTooLargeError, return empty array to gracefully handle
			return [];
		}
	}

	private async getDepartmentHistoricalAverage(datasetId: string, dept: string): Promise<number> {
		const query = {
			WHERE: {
				IS: {[`${datasetId}_dept`]: dept}
			},
			OPTIONS: {
				COLUMNS: ["avgGrade"]
			},
			TRANSFORMATIONS: {
				GROUP: [`${datasetId}_dept`],
				APPLY: [{
					avgGrade: {
						AVG: `${datasetId}_avg`
					}
				}]
			}
		};

		const results = await this.facade.performQuery(query);
		return results.length > 0 ? results[0].avgGrade as number : 0;
	}

	private async getTopCoursesByEnrollment(datasetId: string, dept: string): Promise<CourseInsight[]> {
		const query = {
			WHERE: {
				IS: {[`${datasetId}_dept`]: dept}
			},
			OPTIONS: {
				COLUMNS: [`${datasetId}_dept`, `${datasetId}_id`, `${datasetId}_title`, "totalEnrollment", "avgGrade"],
				ORDER: {
					dir: "DOWN",
					keys: ["totalEnrollment"]
				}
			},
			TRANSFORMATIONS: {
				GROUP: [`${datasetId}_dept`, `${datasetId}_id`, `${datasetId}_title`],
				APPLY: [
					{
						totalEnrollment: {
							SUM: `${datasetId}_pass`
						}
					},
					{
						avgGrade: {
							AVG: `${datasetId}_avg`
						}
					}
				]
			}
		};

		const results = await this.facade.performQuery(query);
		return results.map((r: InsightResult) => ({
			dept: r[`${datasetId}_dept`] as string,
			id: r[`${datasetId}_id`] as string,
			title: r[`${datasetId}_title`] as string,
			enrollment: r.totalEnrollment as number,
			average: r.avgGrade as number
		}));
	}

	private async getHighestAverageCourses(datasetId: string, dept: string): Promise<CourseInsight[]> {
		const query = {
			WHERE: {
				IS: {[`${datasetId}_dept`]: dept}
			},
			OPTIONS: {
				COLUMNS: [`${datasetId}_dept`, `${datasetId}_id`, `${datasetId}_title`, "totalEnrollment", "avgGrade"],
				ORDER: {
					dir: "DOWN",
					keys: ["avgGrade"]
				}
			},
			TRANSFORMATIONS: {
				GROUP: [`${datasetId}_dept`, `${datasetId}_id`, `${datasetId}_title`],
				APPLY: [
					{
						totalEnrollment: {
							SUM: `${datasetId}_pass`
						}
					},
					{
						avgGrade: {
							AVG: `${datasetId}_avg`
						}
					}
				]
			}
		};

		const results = await this.facade.performQuery(query);
		return results.map((r: InsightResult) => ({
			dept: r[`${datasetId}_dept`] as string,
			id: r[`${datasetId}_id`] as string,
			title: r[`${datasetId}_title`] as string,
			enrollment: r.totalEnrollment as number,
			average: r.avgGrade as number
		}));
	}
}