// Code generated by Claude Sonnet 4 and adjusted as needed by Elena Kolmogorov and Alex Kwok
import {
	IInsightFacade,
	InsightDataset,
	InsightDatasetKind,
	InsightResult,
	InsightError,
	NotFoundError,
	ResultTooLargeError,
} from "./IInsightFacade";
import { Section } from "./Section";
import * as fs from "fs-extra";

import { QueryValidator } from "./QueryValidator";
import { DatasetValidator } from "./DatasetValidator";

export default class InsightFacade implements IInsightFacade {
	private static readonly MAX_RESULTS = 5000;
	private static readonly OVERALL_YEAR = 1900;
	private static readonly JSON_EXTENSION_LENGTH = 5;

	private readonly persistDir: string = "./data";
	private queryValidator = new QueryValidator();
	private datasetValidator = new DatasetValidator();
	private datasets = new Map<string, Section[]>();
	private loadPromise: Promise<void>;

	constructor() {
		this.datasets = new Map<string, Section[]>();
		this.loadPromise = this.loadPersistedDatasets();
	}

	public async addDataset(id: string, content: string, kind: InsightDatasetKind): Promise<string[]> {
		await this.loadPromise;

		this.datasetValidator.validateId(id);

		if (this.datasets.has(id)) {
			throw new InsightError(`Dataset with id '${id}' already exists`);
		}

		if (kind !== InsightDatasetKind.Sections) {
			throw new InsightError("Only 'sections' kind is supported");
		}

		const sections = await this.datasetValidator.extractSectionsFromZip(content);

		if (sections.length === 0) {
			throw new InsightError("No valid sections found in dataset");
		}

		this.datasets.set(id, sections);

		try {
			await this.saveToDisk(id, sections);
		} catch (error) {
			this.datasets.delete(id);
			throw new InsightError(`Failed to persist dataset: ${error}`);
		}

		return Array.from(this.datasets.keys());
	}

	private async saveToDisk(id: string, sections: Section[]): Promise<void> {
		await fs.ensureDir(this.persistDir);
		const filepath = `${this.persistDir}/${id}.json`;
		await fs.writeJSON(filepath, sections, { spaces: 2 });
	}

	private async loadPersistedDatasets(): Promise<void> {
		try {
			const exists = await fs.pathExists(this.persistDir);
			if (!exists) {
				return;
			}
			const files = await fs.readdir(this.persistDir);

			const loadPromises = files
				.filter((file) => file.endsWith(".json"))
				.map(async (file) => {
					try {
						const filepath = `${this.persistDir}/${file}`;
						const sections: Section[] = await fs.readJSON(filepath);
						const datasetId = file.slice(0, -InsightFacade.JSON_EXTENSION_LENGTH);
						return { datasetId, sections };
					} catch {
						return null;
					}
				});

			const results = await Promise.all(loadPromises);

			for (const result of results) {
				if (result !== null) {
					this.datasets.set(result.datasetId, result.sections);
				}
			}
		} catch {
			// Start with empty datasets
		}
	}

	public async removeDataset(id: string): Promise<string> {
		// await this.loadPromise;

		this.datasetValidator.validateId(id);

		if (!this.datasets.has(id)) {
			throw new NotFoundError(`Dataset with id '${id}' not found`);
		}

		this.datasets.delete(id);

		try {
			const filepath = `${this.persistDir}/${id}.json`;
			await fs.remove(filepath);
		} catch {
			// If disk removal fails, we should still consider it removed from memory
		}
		return id;
	}

	public async listDatasets(): Promise<InsightDataset[]> {
		// await this.loadPromise;

		const result: InsightDataset[] = [];

		for (const [id, sections] of this.datasets.entries()) {
			result.push({
				id: id,
				kind: InsightDatasetKind.Sections,
				numRows: sections.length,
			});
		}

		return result;
	}

	public async performQuery(query: unknown): Promise<InsightResult[]> {
		if (!query || typeof query !== "object" || Array.isArray(query)) {
			throw new InsightError("Query must be an object");
		}

		const q = query as Record<string, any>;
		this.queryValidator.validateQueryStructure(q);

		const datasetId = this.extractDatasetId(q);
		if (!datasetId) {
			throw new InsightError("Query must reference exactly one dataset");
		}

		// await this.loadPromise;
		const dataset = this.datasets.get(datasetId);
		if (!dataset) {
			throw new InsightError(`Dataset ${datasetId} not found`);
		}

		const filtered = this.applyWhere(dataset, q.WHERE);
		// improved efficiency from AI's version - EK
		if (filtered.length > InsightFacade.MAX_RESULTS) {
			throw new ResultTooLargeError("Query result exceeds 5000 rows");
		}

		const results = this.applyOptions(filtered, q.OPTIONS);
		return results;
	}

	private extractDatasetId(query: Record<string, any>): string | null {
		const keys = new Set<string>();
		this.collectKeys(query, keys);
		const ids = [
			...new Set(
				Array.from(keys).map((k) => k.split("_")[0])
				// .filter(Boolean) removed this from AI's version because it masks bugs. EK
			),
		];
		return ids.length === 1 ? ids[0] : null;
	}

	private collectKeys(obj: any, keys: Set<string>): void {
		if (typeof obj === "string" && obj.includes("_")) {
			keys.add(obj);
		} else if (Array.isArray(obj)) {
			obj.forEach((item) => this.collectKeys(item, keys));
		} else if (obj && typeof obj === "object") {
			Object.values(obj).forEach((value) => this.collectKeys(value, keys));
		}
	}

	private applyWhere(dataset: Section[], where: any): Section[] {
		if (!where || Object.keys(where).length === 0) return dataset;
		return dataset.filter((section) => this.evaluateFilter(section, where));
	}

	private evaluateFilter(section: Section, filter: any): boolean {
		// fixed this from AI's version - EK. No defensive programming and masking of bugs.
		if (!filter || typeof filter !== "object") throw new InsightError("Invalid filter");

		const [key, value] = Object.entries(filter)[0];
		switch (key) {
			case "AND":
				return Array.isArray(value) && value.every((f) => this.evaluateFilter(section, f));
			case "OR":
				return Array.isArray(value) && value.some((f) => this.evaluateFilter(section, f));
			case "NOT":
				return !this.evaluateFilter(section, value);
			case "LT":
				return this.evaluateComparison(section, value, (a, b) => a < b);
			case "GT":
				return this.evaluateComparison(section, value, (a, b) => a > b);
			case "EQ":
				return this.evaluateComparison(section, value, (a, b) => a === b);
			case "IS":
				return this.evaluateStringComparison(section, value);
			default:
				return false;
		}
	}

	private evaluateComparison(section: Section, comparison: any, op: (a: number, b: number) => boolean): boolean {
		const [fieldKey, expectedValue] = Object.entries(comparison)[0];
		const field = fieldKey.split("_")[1];
		const value = (section as any)[field];
		return typeof value === "number" && op(value, expectedValue as number);
	}

	private evaluateStringComparison(section: Section, comparison: any): boolean {
		const [fieldKey, pattern] = Object.entries(comparison)[0];
		const field = fieldKey.split("_")[1];
		const value = (section as any)[field];
		if (typeof value !== "string" || typeof pattern !== "string") return false;

		const startWild = pattern.startsWith("*");
		const endWild = pattern.endsWith("*");
		const cleanPattern = pattern.replace(/^\*|\*$/g, "");

		if (startWild && endWild) return value.includes(cleanPattern);
		if (startWild) return value.endsWith(cleanPattern);
		if (endWild) return value.startsWith(cleanPattern);
		return value === cleanPattern;
	}

	private applyOptions(sections: Section[], options: any): InsightResult[] {
		//takes filtered sections and query options, returns array of InsightResult objects.
		const results = sections.map((section) => {
			const result: InsightResult = {};
			options.COLUMNS.forEach((col: string) => {
				const field = col.split("_")[1];
				result[col] = (section as any)[field];
			});
			return result;
		});

		if (options.ORDER) {
			const orderKey = options.ORDER;
			results.sort((a, b) => {
				const aVal = a[orderKey];
				const bVal = b[orderKey];
				if (typeof aVal === "number" && typeof bVal === "number") {
					return aVal - bVal;
				}
				return String(aVal).localeCompare(String(bVal));
			});
		}
		return results;
	}
}
// End Code generated by Claude Sonnet 4 and adjusted as needed by Elena Kolmogorov and Alex Kwok
