// Code generated by Claude Sonnet 4 and adjusted as needed by Elena Kolmogorov and Alex Kwok
import { InsightError } from "./IInsightFacade";

// === START: Amazon Q Implementation ===
export class QueryValidator {
	public validateQueryStructure(q: Record<string, any>): void {
		if (!q.WHERE || !q.OPTIONS) {
			throw new InsightError("Query must have WHERE and OPTIONS");
		}
		const keys = Object.keys(q);
		const validKeys = ["WHERE", "OPTIONS", "TRANSFORMATIONS"];
		if (!keys.every((key) => validKeys.includes(key))) {
			throw new InsightError("Query contains invalid keys");
		}
		const MAX_QUERY_KEYS = 3;
		if (keys.length < 2 || keys.length > MAX_QUERY_KEYS) {
			throw new InsightError("Query must have WHERE, OPTIONS, and optionally TRANSFORMATIONS");
		}
		this.validateWhere(q.WHERE);
		if (q.TRANSFORMATIONS) {
			this.validateTransformations(q.TRANSFORMATIONS);
		}
		this.validateOptions(q.OPTIONS, q.TRANSFORMATIONS);
	}

	private validateWhere(where: any): void {
		if (typeof where !== "object" || Array.isArray(where)) {
			throw new InsightError("WHERE must be an object");
		}
		if (Object.keys(where).length > 0) {
			// Non-empty WHERE; i.e. if length is 0, it's empty and matches all entries
			this.validateFilter(where);
		}
	}

	private validateFilter(filter: any): void {
		if (!filter || typeof filter !== "object" || Array.isArray(filter)) {
			throw new InsightError("Filter must be an object");
		}
		const keys = Object.keys(filter);
		if (keys.length !== 1) {
			throw new InsightError("Filter must have exactly one key");
		}
		const [key, value] = Object.entries(filter)[0];
		switch (key) {
			case "AND":
			case "OR":
				if (!Array.isArray(value) || value.length === 0) {
					throw new InsightError(`${key} must be a non-empty array`);
				}
				value.forEach((f: any) => this.validateFilter(f));
				break;
			case "NOT":
				if (Array.isArray(value)) {
					throw new InsightError("NOT cannot wrap an array");
				}
				this.validateFilter(value);
				break;
			case "LT":
			case "GT":
			case "EQ":
				this.validateMComparison(value);
				break;
			case "IS":
				this.validateSComparison(value);
				break;
			default:
				throw new InsightError(`Invalid filter key: ${key}`);
		}
	}

	private validateMComparison(comparison: any): void {
		if (!comparison || typeof comparison !== "object" || Array.isArray(comparison)) {
			throw new InsightError("Comparison must be an object");
		}
		const keys = Object.keys(comparison);
		if (keys.length !== 1) {
			throw new InsightError("Comparison must have exactly one key");
		}
		const [fieldKey, expectedValue] = Object.entries(comparison)[0];
		if (typeof expectedValue !== "number") {
			throw new InsightError("Comparison value must be a number");
		}
		this.validateKey(fieldKey, "mfield");
	}

	private validateSComparison(comparison: any): void {
		if (!comparison || typeof comparison !== "object" || Array.isArray(comparison)) {
			throw new InsightError("IS comparison must be an object");
		}
		const keys = Object.keys(comparison);
		if (keys.length !== 1) {
			throw new InsightError("IS comparison must have exactly one key");
		}
		const [fieldKey, pattern] = Object.entries(comparison)[0];
		if (typeof pattern !== "string") {
			throw new InsightError("IS comparison value must be a string");
		}
		this.validateWildcard(pattern);
		this.validateKey(fieldKey, "sfield");
	}

	private validateWildcard(pattern: string): void {
		const asteriskCount = (pattern.match(/\*/g) || []).length;
		if (asteriskCount > 2) {
			throw new InsightError("Too many asterisks in pattern");
		}
		if (asteriskCount === 2 && (!pattern.startsWith("*") || !pattern.endsWith("*"))) {
			throw new InsightError("Asterisks can only be at the beginning and/or end");
		}
		if (asteriskCount === 1 && !pattern.startsWith("*") && !pattern.endsWith("*")) {
			throw new InsightError("Asterisks can only be at the beginning and/or end");
		}
	}

	private validateKey(key: string, expectedType: "mfield" | "sfield"): void {
		if (!key.includes("_")) {
			throw new InsightError("Key must contain underscore");
		}
		const parts = key.split("_");
		if (parts.length !== 2 || parts[0] === "" || parts[1] === "") {
			throw new InsightError("Invalid key format");
		}
		const [, field] = parts;
		const mfields = ["avg", "pass", "fail", "audit", "year", "lat", "lon", "seats"];
		const sfields = [
			"dept",
			"id",
			"instructor",
			"title",
			"uuid",
			"fullname",
			"shortname",
			"number",
			"name",
			"address",
			"type",
			"furniture",
			"href",
		];
		if (expectedType === "mfield" && !mfields.includes(field)) {
			throw new InsightError(`Invalid mfield: ${field}`);
		}
		if (expectedType === "sfield" && !sfields.includes(field)) {
			throw new InsightError(`Invalid sfield: ${field}`);
		}
	}

	private validateTransformations(transformations: any): void {
		if (!transformations || typeof transformations !== "object" || Array.isArray(transformations)) {
			throw new InsightError("TRANSFORMATIONS must be an object");
		}
		if (!transformations.GROUP || !transformations.APPLY) {
			throw new InsightError("TRANSFORMATIONS must have GROUP and APPLY");
		}
		const keys = Object.keys(transformations);
		if (keys.length !== 2) {
			throw new InsightError("TRANSFORMATIONS must have exactly GROUP and APPLY");
		}
		this.validateGroup(transformations.GROUP);
		this.validateApply(transformations.APPLY);
	}

	private validateGroup(group: any): void {
		if (!Array.isArray(group)) {
			throw new InsightError("GROUP must be an array");
		}
		if (group.length === 0) {
			throw new InsightError("GROUP must not be empty");
		}
		group.forEach((key: any) => {
			if (typeof key !== "string") {
				throw new InsightError("GROUP keys must be strings");
			}
			this.validateKey(key, this.getKeyType(key));
		});
	}

	private validateApply(apply: any): void {
		if (!Array.isArray(apply)) {
			throw new InsightError("APPLY must be an array");
		}
		const applyKeys = new Set<string>();
		apply.forEach((rule: any) => {
			if (!rule || typeof rule !== "object" || Array.isArray(rule)) {
				throw new InsightError("APPLY rule must be an object");
			}
			const ruleKeys = Object.keys(rule);
			if (ruleKeys.length !== 1) {
				throw new InsightError("APPLY rule must have exactly one key");
			}
			const applyKey = ruleKeys[0];
			if (applyKey.includes("_")) {
				throw new InsightError("Apply key cannot contain underscores");
			}
			if (applyKeys.has(applyKey)) {
				throw new InsightError("Apply keys must be unique");
			}
			applyKeys.add(applyKey);
			this.validateApplyRule(rule[applyKey]);
		});
	}

	private validateApplyRule(rule: any): void {
		if (!rule || typeof rule !== "object" || Array.isArray(rule)) {
			throw new InsightError("Apply rule must be an object");
		}
		const keys = Object.keys(rule);
		if (keys.length !== 1) {
			throw new InsightError("Apply rule must have exactly one operation");
		}
		const [operation, field] = Object.entries(rule)[0];
		const validOperations = ["MAX", "MIN", "AVG", "SUM", "COUNT"];
		if (!validOperations.includes(operation)) {
			throw new InsightError(`Invalid apply operation: ${operation}`);
		}
		if (typeof field !== "string") {
			throw new InsightError("Apply field must be a string");
		}
		if (operation === "COUNT") {
			this.validateKey(field, this.getKeyType(field));
		} else {
			this.validateKey(field, "mfield");
		}
	}

	private validateOptions(options: any, transformations?: any): void {
		if (!options || typeof options !== "object" || Array.isArray(options)) {
			throw new InsightError("OPTIONS must be an object");
		}
		if (!options.COLUMNS) {
			throw new InsightError("OPTIONS must have COLUMNS");
		}
		if (!Array.isArray(options.COLUMNS) || options.COLUMNS.length === 0) {
			throw new InsightError("COLUMNS must be a non-empty array");
		}
		const validOptionKeys = ["COLUMNS", "ORDER"];
		const optionKeys = Object.keys(options);
		optionKeys.forEach((key) => {
			if (!validOptionKeys.includes(key)) {
				throw new InsightError(`Invalid OPTIONS key: ${key}`);
			}
		});

		const applyKeys = transformations ? this.getApplyKeys(transformations.APPLY) : [];
		const groupKeys = transformations ? transformations.GROUP : [];

		options.COLUMNS.forEach((col: any) => {
			if (typeof col !== "string") {
				throw new InsightError("Column must be a string");
			}
			if (transformations) {
				if (!groupKeys.includes(col) && !applyKeys.includes(col)) {
					throw new InsightError("COLUMNS must only contain GROUP keys or APPLY keys when TRANSFORMATIONS is present");
				}
			} else {
				this.validateKey(col, this.getKeyType(col));
			}
		});

		if (options.ORDER) {
			this.validateOrder(options.ORDER, options.COLUMNS);
		}
	}

	private validateOrder(order: any, columns: string[]): void {
		if (typeof order === "string") {
			if (!columns.includes(order)) {
				throw new InsightError("ORDER key must be in COLUMNS");
			}
		} else if (typeof order === "object" && !Array.isArray(order)) {
			if (!order.dir || !order.keys) {
				throw new InsightError("ORDER object must have dir and keys");
			}
			if (order.dir !== "UP" && order.dir !== "DOWN") {
				throw new InsightError("ORDER dir must be UP or DOWN");
			}
			if (!Array.isArray(order.keys) || order.keys.length === 0) {
				throw new InsightError("ORDER keys must be a non-empty array");
			}
			order.keys.forEach((key: any) => {
				if (typeof key !== "string") {
					throw new InsightError("ORDER keys must be strings");
				}
				if (!columns.includes(key)) {
					throw new InsightError("All ORDER keys must be in COLUMNS");
				}
			});
		} else {
			throw new InsightError("ORDER must be a string or object");
		}
	}

	private getApplyKeys(apply: any[]): string[] {
		return apply.map((rule) => Object.keys(rule)[0]);
	}

	private getKeyType(key: string): "mfield" | "sfield" {
		const field = key.split("_")[1];
		const mfields = ["avg", "pass", "fail", "audit", "year", "lat", "lon", "seats"];
		return mfields.includes(field) ? "mfield" : "sfield";
	}
}
// === END: Amazon Q Implementation ===
// Code generated by Claude Sonnet 4 and adjusted as needed by Elena Kolmogorov and Alex Kwok
